apiVersion: v1
kind: PersistentVolume
metadata:
 name: pvnijntje
spec:
 capacity:
   storage: 200Mi  
 accessModes:
 - ReadWriteOnce  
 nfs:  
   path: /srv/rabbit2
   server: 10.50.104.83
 persistentVolumeReclaimPolicy: Retain
