apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose --provider openshift --file cluster.yaml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nijntje
  name: nijntje
spec:
  ports:
  - name: "4369"
    port: 4369
    targetPort: 4369
  - name: "5671"
    port: 5671
    targetPort: 5671
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15671"
    port: 15671
    targetPort: 15671
  - name: "15672"
    port: 15672
    targetPort: 15672
  - name: "25672"
    port: 25672
    targetPort: 25672
  selector:
    io.kompose.service: nijntje
status:
  loadBalancer: {}
