apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: ./kompose --provider openshift --file cluster.yaml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nijntje
  name: slaafje
spec:
  replicas: 1
  selector:
    io.kompose.service: slaafje
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: slaafje
    spec:
      containers:
      - env:
        - name: RABBITMQ_ERLANG_COOKIE
          value: nomnom
        - name: RABBITMQ_NODENAME
          value: slaafje
        image: ' '
        name: rabbit1
        ports:
        - containerPort: 4369
        - containerPort: 5671
        - containerPort: 5672
        - containerPort: 15671
        - containerPort: 15672
        - containerPort: 25672
        resources: {}
      hostname: slaafje
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - rabbit1
      from:
        kind: ImageStreamTag
        name: rabbit:latest
    type: ImageChange
status: {}
