apiVersion: v1
kind: Template
metadata:
  name: rabbit
  annotations:
    description: "Description"
    iconClass: "rabbitmq"
    tags: "builder,rabbitmq,messagebus"
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: rabbitmq
      annotations:
        description: Defines how to build the application
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}" 
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${CONTEXT_DIR}"
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: rabbitmq
    spec:
      replicas: "${{REPLICA_COUNT}}" 
- apiVersion: v1
  kind: Pod
  metadata:
    name: nijntje
  spec:
    containers:
    - env:
      - name: RABBITMQ_DEFAULT_PASS
        value: ${RABBITMQ_DEFAULT_PASS}
      - name: RABBITMQ_DEFAULT_USER
        value: ${RABBITMQ_DEFAULT_USER}
      - name: RABBITMQ_ERLANG_COOKIE
        value: ${RABBITMQ_ERLANG_COOKIE}
      image: dockerfile/rabbitmq:3.7-management
      name: nijtje
      ports:
      - containerPort: 15672
        protocol: TCP
      - containerPort: 5672
        protocol: TCP

parameters:
- description: Password used for admin authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: RABBITMQ_DEFAULT_PASS
labels:
  redis: nijntje
